[build-system]
requires = ["setuptools>=51", "wheel", "setuptools_scm[toml]>=6"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79

[tool.isort]
line_length = 79
lines_after_imports = 2
profile = "black"

[tool.setuptools_scm]
write_to = "src/pfh/glidersim/_version.py"
